baseURL = 'https://bluedotiowa.com/'
languageCode = 'en-us'
title = 'Blue Dot Iowa'
theme = 'PaperMod'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[pagination]
pagerSize = 5

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = " Blue Dot Iowa"
description = "Blue Dot Iowa"
keywords = [ "Iowa", "Blue Dot"]
author = "Blue Dot Iowa"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
#ShareButtons = ["bluesky", "reddit"]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "favicon.ico"
#  favicon16x16 = "<link / abs url>"
#  favicon32x32 = "<link / abs url>"
#  apple_touch_icon = "<link / abs url>"
#  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Blue Dot Iowa"
#  icon = "/apple-touch-icon.png"
#  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Blue Dot Iowa"
  subtitle = "Making Connections"
  imageUrl = "favicon.ico"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Blue Dot"

    [[params.profileMode.buttons]]
    name = "Resources"
    url = "/posts/resources"

    [[params.profileMode.buttons]]
    name = "Advice"
    url = "/posts/advice"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

#  [[params.socialIcons]]
#  name = "x"
#  url = "https://x.com/"

#  [[params.socialIcons]]
#  name = "stackoverflow"
#  url = "https://stackoverflow.com"

#  [[params.socialIcons]]
#  name = "github"
#  url = "https://github.com/"

  [[params.socialIcons]]
  name = "bluesky"
  url = "https://bsky.app/profile/bluedotiniowa.bsky.social"
  #https://bluesky.com/

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

#  [params.editPost]
#  URL = "https://github.com/<path_to_repo>/content"
#  Text = "Suggest Changes"
#  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "resources"
name = "Resources"
url = "/posts/resources/"
weight = 10

[[menu.main]]
identifier = "advice"
name = "Advice"
url = "/posts/advice/"
weight = 10

# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 20

[[menu.main]]
identifier = "bluesky"
name = "BlueSky"
url = "https://bsky.app/profile/bluedotiniowa.bsky.social"
weight = 30

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true